version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: test_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TwitterClone
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5